### PR TITLE
Migrate Circle CI to Github CI

### LINKED ISSUE #189: spring-boot-bom: Migrate Circle CI to Github CI

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/snowdrop/spring-boot-bom/issues/189

### CODE REVIEW

**Comment by jacobdotcosta** [comment]
In the test logs I see references to SpringBoot 2.4. This might probably be due to the fact that the examples aren't updated yet to SB 2.5, I'll take a look.

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Boot - HTTP Example 2.4.9-14-SNAPSHOT
[INFO] ------------------------------------------------------------------------
```

**Comment by Sgitario** [comment]
> In the test logs I see references to SpringBoot 2.4. This might probably be due to the fact that the examples aren't updated yet to SB 2.5, I'll take a look.
> 
> ```
> [INFO] Scanning for projects...
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Spring Boot - HTTP Example 2.4.9-14-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> ```

Yes. I thought you were already aware of it as the bom parent version is still 2.4.

**Comment by jacobdotcosta** [comment]
I have yet to update the `2.5.x` branches of the examples and the testsuite.

**Comment by jacobdotcosta** [comment]
LGTM

**Review by jacobdotcosta — APPROVED** [review]

**Pull request merged**
