### PR TITLE
Move parent dm

### PR DESCRIPTION
**Pull request by jacobdotcosta**

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
From Spring Boot documentation (https://docs.spring.io/spring-boot/docs/2.6.4/maven-plugin/reference/htmlsingle/#using.parent-pom), they recommend to use the parent `spring-boot-starter-parent` instead of `spring-boot-dependencies`.

Moreover, the dependency `spring-boot-dependencies` must be declared in the end so the others dependencies take precedence (see https://docs.spring.io/spring-boot/docs/2.6.4/maven-plugin/reference/htmlsingle/#using.import)

**Comment by jacobdotcosta** [comment]
> From Spring Boot documentation (https://docs.spring.io/spring-boot/docs/2.6.4/maven-plugin/reference/htmlsingle/#using.parent-pom), they recommend to use the parent `spring-boot-starter-parent` instead of `spring-boot-dependencies`.
> 

I'm not sure about this as adding the parent will add several plugins that we aren't using. Using the `spring-boot-starter-parent` might bring too much configuration.

> Moreover, the dependency `spring-boot-dependencies` must be declared in the end so the others dependencies take precedence (see https://docs.spring.io/spring-boot/docs/2.6.4/maven-plugin/reference/htmlsingle/#using.import)

Moved the dependency to the end.

**Review by Sgitario — APPROVED** [review]

**Comment by Sgitario** [comment]
@jacobdotcosta this CI is failing, maybe this solution didn't work?

**Comment by jacobdotcosta** [comment]
> @jacobdotcosta this CI is failing, maybe this solution didn't work?

That's what I'm trying to understand. It isn't failing as before as now the problem is a timeout on the tests, and it's the 2nd run, so something might not be right. 

```
Error:  Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 137.915 s <<< FAILURE! - in dev.snowdrop.example.ManagedOpenShiftIT
Error:  testGreetingEndpointWithNameParameter  Time elapsed: 2.893 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)

Error:  testGreetingEndpoint  Time elapsed: 0.471 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by jacobdotcosta** [comment]
Fixed. I'm not sure if it was snowdrop/testsuite#9 or simply running it again.

**Pull request merged**
