### PR TITLE
chore: bump infinispan version according to infinispan team indications

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Review by metacosm — COMMENTED** [review]
Can you add a link / reference to the JIRA on which you based that change, please? I think we should start doing this to track why a change was made in the BOM…

**Comment by aureamunoz** [comment]
Sure, good idea.

here the jira: https://issues.redhat.com/browse/JDG-3946

**Comment by metacosm** [comment]
> Sure, good idea.
> 
> here is the jira: https://issues.redhat.com/browse/JDG-3946

Sorry I wasn't clear enough: the ticket should be in the commit comment that introduces the change so that when someone does a `git blame` to see when / how the change was introduced, they can look at the associated JIRA.

**Comment by aureamunoz** [comment]
done. WDYT?

**Comment by aureamunoz** [comment]
Yes, I agree with the latter proposition. I think it could be clearer. I will change it.

**Review by metacosm — CHANGES_REQUESTED** [review]
We need to get the starter version as well so this cannot be merged as-is.

**Pull request closed without merging**
